### ISSUE TITLE
How to integrate

### ISSUE THREAD

**Issue by nebojsa-marinkov** [gauravsoni119/ng2-tel-input#1]
I don't have idea how to integrate this into angular-cli project and how to include css file that doesn't exists

**Comment by mrvnklm** [comment]
me neither, please help

**Comment by gauravsoni119** [comment]
Hi @nebojsa-marinkov  and @mrvnklm , I fixed issue of using this with angular-cli. Moreover, I am working on this directive in order to make it more flexible. I updated readme.md file. Please update your local package.

**Comment by vmula** [comment]
Will this work with angular4? if so, kindly write the step, who to include? I followed the current readme.md and it is not working.
