### ISSUE TITLE
Angular 5 Error

### ISSUE THREAD

**Issue by paxpelus** [gauravsoni119/ng2-tel-input#10]
When doing ng build on angular 5 I am getting the following error

ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /usr/src/app/node_modules/ng2-tel-input/node_modules/@angular/core/core.d.ts, resolving symbol Ng2TelInputModule in /usr/src/app/node_modules/ng2-tel-input/src/ng2-tel-input.module.d.ts, resolving symbol Ng2TelInputModule in /usr/src/app/node_modules/ng2-tel-input/src/ng2-tel-input.module.d.ts

Have you successfully used this library in angular 5.x ?

**Comment by ahmadmsa87** [comment]
Is there any solution for this bug?

**Comment by markm1992** [comment]
Have the same error using Angular5 :(

**Comment by markm1992** [comment]
Actually I got it working by the following steps....
1) delete "app/node_modules/ng2-tel-input/node_modules"
2) Edit the following sections of package.json to...
"devDependencies": {
    "@angular/compiler": "^5.0.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/platform-server": "5.0.0",
    "@types/intl-tel-input": "0.0.8",
    "@types/jquery": "<2.2",
    "http-server": "^0.9.0",
    "typescript": "^2.4.2"
  },
 "dependencies": {
    "@angular/core": "^5.0.0",
    "es6-shim": "^0.35.3",
    "intl-tel-input": "^12.0.3",
    "jquery": "^3.1.1",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.4.1",
    "zone.js": "^0.8.14"
  },

**Comment by gauravsoni119** [comment]
Updated packages to angular5.
