### ISSUE TITLE
@NgModule annotation error in Angular 5

### ISSUE THREAD

**Issue by kaushik-nimble** [gauravsoni119/ng2-tel-input#12]
I am using Angular 5 and I have implemented this plugin.

when run the projects getting this type of error

Uncaught Error: Unexpected value 'Ng2TelInputModule' imported by the module 'AppModule'. Please add a @NgModule annotation.

Is there something I am missing?

Thank you in advance.

**Comment by gauravsoni119** [comment]
@kaushik-nimble updated this package to angular5
