### ISSUE TITLE
phone number not auto formatting after user enter full number

### ISSUE THREAD

**Issue by bigboss0006** [gauravsoni119/ng2-tel-input#14]
I am looking like intl-tel-input phone number auto formats

**Comment by endresh97** [comment]
having same issue. phone number auto formatting not working after entering the full number.

Please give the reply, as soon as possible.

**Comment by gauravsoni119** [comment]
According to the original package, https://github.com/jackocnr/intl-tel-input/issues/346
Autoformat feature is removed in their new versions.

**Comment by ravimutti** [comment]
@gauravsoni119 how can I format a number when the user enters a number.
