### ISSUE TITLE
Do you need to install the original inl-tel-input to get the style working?

### ISSUE THREAD

**Issue by raysunqi** [gauravsoni119/ng2-tel-input#18]

**Comment by mbark** [comment]
This library depends on the original `intl-tel-input` as it is just a thin wrapper around it (it just adds a directive that binds to the `tel-input`. So you can either explicitly install the `intl-tel-input` library or just rely on it via the dependency from this library.

Either way to get the style working you should import the css in your `styles.css` file:
```
@import 'intl-tel-input/build/css/intlTelInput.css';
```

**Comment by gauravsoni119** [comment]
Yes, As the @mbark said, its a wrapper around intl-tel-input. **inl-tel-input** will automatically add to your node_modules when you install this package.
