### ISSUE TITLE
Can't bind to 'ng2TelInputOptions' since it isn't a known property of 'input'.

### ISSUE THREAD

**Issue by idevN** [gauravsoni119/ng2-tel-input#2]
How to fix this error? What should I import to component.ts file?

<input type="text" ng2TelInput
[ng2TelInputOptions]="{initialCountry: 'in'}"
(hasError)="hasError($event)"
(ng2TelOutput)="getNumber($event)"
(countryChange)="onCountryChange($event)" />

**Comment by gauravsoni119** [comment]
@idevN import and add Ng2TelInputModule into your AppModule. Example,
import {Ng2TelInputModule} from 'ng2-intl-tel-input';
