### ISSUE TITLE
How to set favorite countries?

### ISSUE THREAD

**Issue by dcosio89** [gauravsoni119/ng2-tel-input#33]
is there a way that i can set the favorite countries instead of using the default (usa and gb) ?

![image](https://user-images.githubusercontent.com/32721430/52098592-7b890980-2584-11e9-9b09-79cb85c4c65d.png)

**Comment by dcosio89** [comment]
i found the solution... 

<input matInput placeholder="" formControlName="countryCode" ng2TelInput 
### **[ng2TelInputOptions]="{'preferredCountries': ['us', 'ca']}"**  
/>

![image](https://user-images.githubusercontent.com/32721430/52099199-11259880-2587-11e9-8dcc-0ebd8ea0db99.png)

should use: [ng2TelInputOptions]="{'preferredCountries': ['us', 'ca']}"

**Comment by skined90** [comment]
Where did you find a list of all ng2TelInputOptions?

**Comment by Johneddieson** [comment]
how to hide all country except preferredcountries?
