### ISSUE TITLE
 Ng2TelInputModule is not an NgModule

### ISSUE THREAD

**Issue by ShaileshInfyom** [gauravsoni119/ng2-tel-input#4]
i add this line into my module into angular-cli project
import {Ng2TelInputModule} from 'ng2-intl-tel-input'
but i got error  `ng2-intl-tel-input` not a module and i not found `ng2-intl-tel-input` dir into node_module

![image](https://user-images.githubusercontent.com/28335166/32821230-56ae6a3a-c9f8-11e7-9c44-596f807463b1.png)

so, i tried to import `import {Ng2TelInputModule} from 'ng2-tel-input'` but got error.

please help me what i doing wrong.

**Comment by gauravsoni119** [comment]
#2

**Comment by ShaileshInfyom** [comment]
i can't found `ng2-intl-tel-input` into node module

**Comment by gauravsoni119** [comment]
Hi @ShaileshInfyom ,
Facing some issues with angular-cli. Working on it.

**Comment by gauravsoni119** [comment]
Updated package on npm. Please Update on your local.

**Comment by ShaileshInfyom** [comment]
Thanks  for your time. now its working fine for me.
