### ISSUE TITLE
no support for new Ivy renderer in Angular 8

### ISSUE THREAD

**Issue by justvamp** [gauravsoni119/ng2-tel-input#44]
After updating to Angular 8 and enabling new Ivy renderer via `enableIvy: true` there is an error: `There is no format with import statements in ng2-tel-input entry-point`.

**Comment by justvamp** [comment]
The repository looks dead, moving to direct usage of intl-tel-input.

**Comment by gauravsoni119** [comment]
Hi @justvamp , Thanks for raising the issue. I am a little busy with my work. I will update this when I get some time. MeanWhile, If you have some time, feel free to raise a pull request.
