### ISSUE TITLE
After updating to latest version functions stopped working

### ISSUE THREAD

**Issue by akvaliya** [gauravsoni119/ng2-tel-input#53]
I was using older version in my angular 7 project.

I just updated to latest versions & it's giving me errors in functions like `setNumber`.

`this.objTelInput.intlTelInput("setNumber", this._contactNumber);` This is how i was using before where `this.objTelInput` is a object received from `intlTelInputObject` event.

Now i am getting this error `MaterialIntlTelInputComponent.html:5 ERROR TypeError: this.objTelInput.intlTelInput is not a function`

Can anyone tell me what is changed in latest version? How to access methods like `setNumber`, `getNumber`?

**Comment by bendg25** [comment]
Same error for me, on latest Angular 8

**Comment by gctom57** [comment]
Hello,

For me what's worked is doing `this.objTelInput.setNumber(this._contactNumber);` 

Regards

**Comment by akvaliya** [comment]
Thanks. Looks like syntax is changed for using functions.
