### ISSUE TITLE
Not working with ivy

### ISSUE THREAD

**Issue by bendg25** [gauravsoni119/ng2-tel-input#58]
ng2-tel-input.module.js(22,27): error TS-991010: Value at position 0 in the NgModule.declarations of Ng2TelInputModule is not a reference: [object Map]

**Comment by bendg25** [comment]
Seems to work with latest Angular 9 -> RC.6

**Comment by bendg25** [comment]
Value at position 0 in the NgModule.declarations of Ng2TelInputModule is not a reference: [object Object] . scrap that, issue is still there

**Comment by gauravsoni119** [comment]
@bendg25 Thanks for raising the issue. I am looking into this issue. I am going through couple of issues and articles on GitHub such as:-
https://github.com/angular/angular/issues/32025
https://medium.com/@sarunint/how-can-you-experimentally-try-angular-ivy-right-now-c23930062b4c

It seems like the package is not according to the standards of the angular.

**Comment by bendg25** [comment]
Hi, yes that is as far as I got with it.  It was not immediately obvious what Angular is not happy about.

**Comment by Dt-Sodium** [comment]
Awaiting an official fix, there a very easy workaround:
- Copy the two source .ts file from the github in your project
- Import that file instead of the library

The plugin works, it's just the js compilation that Angular is not happy with. I'm not surprised, js is beyond crap.

**Comment by xadim** [comment]
Hello @gauravsoni119 do you have a workaround for this issue please?

Hello @Dt-Sodium importing the .ts file raised other issues on my end, maybe I was not doing it right. Can you please share your workaround code? Thanks-

**Comment by Dt-Sodium** [comment]
I'm not even sure we still use this, another developer finished the telephone number form.
If i remember correctly, i just copied the source .ts file somewhere in my project and imported the class from there.

**Comment by lippomano** [comment]
Hey, any news?

**Comment by gauravsoni119** [comment]
The new version of the package is aligned with [Angular package format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/mobilebasic) which makes it compatible with all angular versions.
