### ISSUE TITLE
Angular 9:  ERROR in Failed to compile entry-point ng2-tel-input (main as commonjs) due to compilation errors:

### ISSUE THREAD

**Issue by nimatullah** [gauravsoni119/ng2-tel-input#63]
I have upgraded my angular to version 9. and I receive this error:

```
ERROR in Failed to compile entry-point ng2-tel-input (main as commonjs) due to compilation errors:
node_modules/ng2-tel-input/src/ng2-tel-input.module.js:22:27 - error NG1010: Value at position 0 in the NgModule.declarations of Ng2TelInputModule is not a reference: [object Object]

22             declarations: [Ng2TelInput],
                             ~~~~~~~~~~~~~
```

can you please look at this issue?

Thanks

**Comment by Filu-82** [comment]
Same issue here after angular upgrade to version 9.

**Comment by kevincaradant** [comment]
Hello

@gauravsoni119 , do you have any idea when you think this issue will be fix ? 

Thank you :)

**Comment by gauravsoni119** [comment]
Thanks for the issue. Updated to angular V9

**Comment by Nhilo94** [comment]
same issue
angular 9

**Comment by kevincaradant** [comment]
which version do you used ? Try V2.1.0 only (for Angular 9). 
It's works for me under Angular 9.
The latest version V2.2.0 is compiled with Angular 8 and don't work with Angular 9

**Comment by Karen1998** [comment]
npm i ng2-tel-input@2.1.0

**Comment by Nhilo94** [comment]
thanks @Karen1998  @kevincaradant
