### ISSUE TITLE
has no exported member 'ɵɵFactoryDef'

### ISSUE THREAD

**Issue by nimatullah** [gauravsoni119/ng2-tel-input#66]
`  "ng2-tel-input": "^2.1.0",`

`ng --version`

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.25
Node: 12.4.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.25
@angular-devkit/build-angular              0.803.25
@angular-devkit/build-optimizer            0.803.25
@angular-devkit/build-webpack              0.803.25
@angular-devkit/core                       8.3.25
@angular-devkit/schematics                 8.3.25
@angular/cdk                               8.2.3
@angular/cli                               8.3.25
@angular/http                              7.2.16
@angular/material                          8.2.3
@angular/pwa                               0.803.25
@ngtools/webpack                           8.3.25
@nguniversal/common                        8.2.6
@nguniversal/express-engine                8.2.6
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        8.3.25
@schematics/update                         0.803.25
rxjs                                       6.5.4
typescript                                 3.4.1
webpack   
```

Error:

```
ERROR in ../node_modules/ng2-tel-input/src/ng2-tel-input.d.ts:18:21 - error TS2694: Namespace '"/Users/nr/workstation/jobsaf-website/application/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

18     static ɵfac: i0.ɵɵFactoryDef<Ng2TelInput>;
```

**Comment by DrineTN** [comment]
i have the same problem

`  _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.3
Node: 12.16.1
OS: win32 x64
Angular: 8.1.3
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.803.25
@angular-devkit/build-optimizer   0.803.25
@angular-devkit/build-webpack     0.803.25
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.1.3
@angular/animations               8.2.14
@angular/cdk                      8.2.3
@angular/flex-layout              7.0.0-beta.24
@angular/material                 8.2.3
@ngtools/webpack                  8.3.25
@schematics/angular               8.1.3
@schematics/update                0.801.3
rxjs                              6.5.4
typescript                        3.4.5
webpack                           4.39.2
`

**Comment by keyboardbreaker** [comment]
I had the same problem updating angular from 7 - 9.

I updated from 7 -8 and received this error, committed those changes.
Then ran: 

ng update @angular/core @angular/cli which should bring you to version 9 of Angular.

which got rid of this error

**Comment by gauravsoni119** [comment]
Related to  #65
